# rikipermana@live.com
name: Deploy Production

on:
  push:
    branches: [ master ]
  
jobs:
  synch-new-code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Synch New Code
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete
        path: ./
        remote_path: ~/devops-test
        remote_host: ${{ secrets.HOST }}
        remote_port: 22
        remote_user: ${{ secrets.USERNAME }}
        remote_key: ${{ secrets.PRIVATE_KEY }}
        
  deploy-container:
    runs-on: ubuntu-latest
    needs: [synch-new-code]
    steps:
    - uses: actions/checkout@v2
    - name: Deploy Container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          cd ~/devops-test
          docker-compose up --build -d